scrape_configs:
  - job_name: kubernetes-pods
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
          - localhost
        labels:
          job: kubernetes-pods
          __path__: /var/log/pods/**/*.log
